#!/bin/bash

PATH=/usr/bin:/home/pi/wiringPi/gpio

# monitoring script for Pi2RMini [ http://awjlogan.wordpress.com ]

echo "Pi2RMini started"

gpio mode 7 out
gpio write 7 0
sudo sleep 2
gpio mode 7 in

# wait for falling edge on GPIO 7
gpio wfi 7 falling
gpio mode 7 out
gpio write 7 0
echo "Pi2RMini Monitor has acknowledged a shutdown."
sudo shutdown -h now
